/*
 * Generated by ISE 22.03.0.0000 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F267_8560();
extern void F269_8722();
extern void F267_8564();
extern void F270_8790();
extern void F272_8954();
extern void F270_8795();
extern void F295_6471();
extern void F307_8406();
extern void F136_2173();
extern EIF_REFERENCE F136_2160();
extern EIF_BOOLEAN F136_2172();
extern EIF_BOOLEAN F136_2180();
extern void F136_2182();
extern void F136_2183();
extern void F136_2184();
extern void F76_1817();
extern EIF_TYPED_VALUE F76_1818();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F267_8560;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F267_8564;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F270_8790;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F270_8795;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F295_6471;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F269_8722;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F272_8954;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F307_8406;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F136_2173;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F136_2172;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F136_2160;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F136_2180;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F136_2182;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F136_2183;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F136_2184;

	egc_str_dtype = 268;

	egc_immstr8_dtype = 267;

	egc_str32_dtype = 271;

	egc_immstr32_dtype = 270;
	egc_arr_dtype = 294;
	egc_tup_dtype = 220;
	egc_disp_rout_id = 3065;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x03A7;
	egc_sp_wchar = 0x03D5;
	egc_sp_bool = 0x0403;
	egc_sp_uint8 = 0x0265;
	egc_sp_uint16 = 0x0293;
	egc_sp_uint32 = 0x02C1;
	egc_sp_uint64 = 0x02EF;
	egc_sp_int8 = 0x031D;
	egc_sp_int16 = 0x034B;
	egc_sp_int32 = 0x0179;
	egc_sp_int64 = 0x0379;
	egc_sp_real32 = 0x0237;
	egc_sp_real64 = 0x0209;
	egc_sp_pointer = 0x06F3;
	egc_sp_ref = 0x01A9;

	egc_uint8_dtype = 243;
	egc_uint16_dtype = 240;
	egc_uint32_dtype = 237;
	egc_uint64_dtype = 234;
	egc_int8_dtype = 231;
	egc_int16_dtype = 228;
	egc_int32_dtype = 225;
	egc_int64_dtype = 222;
	egc_bool_dtype = 258;
	egc_real32_dtype = 246;
	egc_char_dtype = 255;
	egc_wchar_dtype = 252;
	egc_real64_dtype = 249;
	egc_point_dtype = 261;

	egc_exception_dtype = 95;
	egc_except_emnger_dtype = 135;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "account";
	egc_system_location = "C:\\Users\\HP\\Documents\\GitHub\\Proof2Test\\examples\\Eiffel projects\\applications\\account\\EIFGENs\\account\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1681218833;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1847;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1069;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2915;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 6730;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 75;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F76_1817;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F76_1818;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 34; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 178; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 289; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
